name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-celery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build Celery Image
        uses: docker/build-push-action@v5
        with:
          context: ./celery
          load: true
          tags: celery-test:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          
      - name: Run Tests
        run: make test
